In [2]:
import numpy as np

# Array

In [34]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
b = np.array([1,2,3,4,5],float)
print(b)

[ 1.  2.  3.  4.  5.]


In [5]:
data = [1, 2, 3, 4, -8, -10]
c = np.array(data, float)
# Print the reverse NumPy array with type float.
print(c[::-1])

[-10.  -8.   4.   3.   2.   1.]


# Shape and Reshape

In [35]:
# The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

In [21]:
a = np.array([[1, 2],[3, 4],[6,5]])

print(a.shape)     #(3, 2) -> 3 rows and 2 columns 

(3, 2)


In [24]:
a = np.array([1,2,3,4,5,6])

a.shape = (3, 2)

print(a) # the original array has been changed

[[1 2]
 [3 4]
 [5 6]]


In [36]:
# The reshape tool gives a new shape to an array without changing its data.
# It creates a new array and does not modify the original array itself. 

In [26]:
a = np.array([1,2,3,4,5,6])

print(np.reshape(a,(3,2)))

print('\n original array', a) #unchanged array

[[1 2]
 [3 4]
 [5 6]]

 original array [1 2 3 4 5 6]


# Transpose and Flatten

In [28]:
# Transpose will not affect the original array, but it will create a new array.

import numpy

a = numpy.array([[1,2,3],
                [4,5,6]])
print(numpy.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


In [29]:
# Flatten creates a copy of the input array flattened to one dimension.

a = numpy.array([[1,2,3],
                [4,5,6]])
print(a.flatten())

[1 2 3 4 5 6]


# Concatenate

In [31]:
# Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

a = np.concatenate((array_1, array_2, array_3))  

print(a)

[1 2 3 4 5 6 7 8 9]


In [33]:
# If an array has more than one dimension, it is possible to specify the axis along which multiple arrays
# are concatenated. By default, it is along the first dimension axis=0.

import numpy

array_1 = numpy.array([[1,2,3],
                       [0,0,0]])
array_2 = numpy.array([[0,0,0],
                       [7,8,9]])

a = numpy.concatenate((array_1, array_2), axis = 1)

print(a)

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


# Zeros and Ones

In [2]:
import numpy as np
a = np.zeros((3,3), dtype=np.int)
b = np.ones((4,4)) # default dtype is float
print(a)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


# Eye and Identity

In [40]:
# The identity tool returns an identity array. An identity array is a square matrix with
# all the main diagonal elements as 1 and the rest as 0. The default type of elements is float.

np.identity(3) # 3 mean dimension 3x3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [44]:
# The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere
# The diagonal position denpends on k value

np.eye(7, 8, k=2)

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])